/**
 * Headless entry point: everything in `@credda/js` except the React provider
 * and hooks. Zero `react`/`react-dom` runtime dependency, so this is safe to
 * import from plain Node (CLIs, servers, the MCP server in `packages/mcp`)
 * without pulling React into the module graph. Same underlying `lib/*`
 * modules as the default `.` export, just without `components/`/`hooks/`.
 */

// Offline credential verification (compact + W3C VC-JWT) + revocation
export { verifyTrustCredential, verifyVerifiableCredential, isCredentialRevoked } from './lib/credential.js';
export type {
  VerifiedCredential,
  TrustCredentialFacts,
  VerifyOptions,
  VerifiedVc,
  VerifyVcOptions,
  CredentialStatusEntry,
} from './lib/credential.js';

// Portable trust export verification
export { verifyTrustExport } from './lib/trustExport.js';
export type { VerifiedTrustExport } from './lib/trustExport.js';

// Webhook verification (for platforms receiving Credda trust events)
export { verifyWebhookSignature, constructWebhookEvent } from './lib/webhook.js';
export type {
  WebhookEvent, WebhookEventType, VerifyWebhookInput, WebhookVerification,
  ScoreEventData, DisputeResolvedData, MonitorTriggeredData, UsageQuotaWarningData,
  ScoreUpdatedEvent, ScoreBandChangedEvent, DisputeResolvedEvent, MonitorTriggeredEvent, UsageQuotaWarningEvent,
} from './lib/webhook.js';

// Web Bot Auth (RFC 9421) verification: the OPTIONAL second signature on a
// delivery, for receivers that terminate their own edge instead of relying on a
// WAF. Never a substitute for verifyWebhookSignature.
export { verifyWebBotAuthSignature } from './lib/webBotAuth.js';
export type {
  VerifyWebBotAuthInput, WebBotAuthVerification, WebBotAuthDirectory, WebBotAuthJwk,
} from './lib/webBotAuth.js';

// Client (for headless / non-React usage)
export { CreddaClient, CreddaError } from './lib/client.js';
export type {
  CreddaConfig,
  Plan,
  PlanFeature,
  PlanCatalog,
  BenchmarkCatalog,
  BenchmarkStatistics,
  BenchmarkCohort,
  BenchmarkDistributionPayload,
  UserBenchmarkPayload,
  WebhookEventDoc,
  WebhookEventCatalog,
  CreddaErrorContext,
  ErrorCodeDoc,
  ErrorCatalog,
  EnumValueDoc,
  EnumDoc,
  EnumCatalog,
  ChangelogEntry,
  DeprecationNotice,
  ApiChangelog,
  // Adverse-action reason codes. `insufficientData` / `dataState` /
  // `informationalFactors` are what a caller branches on so an ABSENT
  // measurement never becomes an adverse reason.
  ReasonCodeDoc,
  ReasonCodeCatalog,
  ReasonCodeInstance,
  ReasonCodeResult,
  ReasonCodeDirection,
  ReasonCodeDataState,
  InformationalReasonCode,
  TimelinessDisclosure,
  TrustPayload,
  TrustExport,
  AgentDeclaration,
  RegisterAgentInput,
  AgentSubject,
  AgentDetail,
  DeliveryRecord,
  DeliveryRecordDisclaimer,
  DeliveryReceiptsPayload,
  DidDocument,
  RegistryIssuer,
  TrustRegistry,
  CredentialIssuerMetadata,
  CredentialOfferResult,
  ScorePayload,
  ScoreBreakdown,
  ScoreExplainPayload,
  ScoreExplainFactor,
  TrustSummaryPayload,
  ScoreHistoryPayload,
  ScoreDeltaPayload,
  ScoreComponent,
  ScoreComponentsPayload,
  DataSufficiency,
  EarningsQuery,
  VerifiedEarnings,
  EarningsSummary,
  EarningsPeriod,
  EarningsPlatformTotal,
  EarningsWindow,
  EarningsCredentialResult,
  TimelinePayload,
  TimelineItem,
  FactorDelta,
  ProjectionEventInput,
  ProjectionEventType,
  ScoreProjectionPayload,
  BatchScoreEntry,
  BatchScoresPayload,
  PlatformsPayload,
  ContributingPlatform,
  RiskPayload,
  UsagePayload,
  UsageDay,
  ReportEventInput,
  ConfirmerType,
  ReportEventResult,
  IngestEventType,
  ShareTokenResult,
  DisputeOutcome,
  DisputeResult,
  CreateWebhookInput,
  CreateWebhookResult,
  UpdateWebhookInput,
  WebhookConfig,
  WebhookSubscriptionEvent,
  WebhookTestResult,
  WebhookDelivery,
  RecentWebhookEvent,
  RecentWebhookEventDelivery,
  RecentWebhookEventsPayload,
  ScoreMonitor,
  CreateMonitorInput,
  UpdateMonitorInput,
  MonitorListPayload,
  ScreeningStatus,
  ScreeningJob,
  ScreeningResultItem,
  ScreeningListPayload,
  ScreeningResultsPayload,
  IngestTransform,
  IngestFieldRule,
  IngestMapping,
  IngestInput,
  IngestResultItem,
  IngestPayload,
  CreateMappingInput,
  StoredMapping,
  MappingListPayload,
  CreateImportInput,
  ImportStatus,
  ImportJob,
  ImportListPayload,
  ImportRowError,
  ImportRowWarning,
  ImportErrorsPayload,
  ConfirmationStatus,
  ConfirmationDecision,
  CreateConfirmationInput,
  ConfirmationRequest,
  ConfirmationCreateResult,
  ConfirmationBatchResult,
  ConfirmationListPayload,
  ConfirmationPreview,
  ConfirmationRespondResult,
  ActivationRow,
  CreateActivationCampaignInput,
  ActivationCampaignResult,
  ActivationFunnel,
  ActivationCampaignFunnelPayload,
  ReferenceRequestStatus,
  ReferenceDecision,
  ReferenceCategory,
  CreateReferenceInput,
  ReferenceRequest,
  ReferenceCreateResult,
  ReferenceListPayload,
  ReferencePreview,
  ReferenceRespondResult,
  PolicyMetric,
  PolicyDirection,
  PolicyComponentKey,
  PolicyConditionStatus,
  PolicyConditionUnreachable,
  ThresholdPolicy,
  CreatePolicyInput,
  UpdatePolicyInput,
  ThresholdPolicyListPayload,
  OpenBadgeAchievement,
  OpenBadgeAchievementsPayload,
  QualificationCategory,
  QualificationBreakdown,
  VerifiedProfilePayload,
  RecordQualificationInput,
  QualificationImportItemInput,
  RecordQualificationResult,
  ProvenanceTier,
  RecordedProvenance,
  QualificationImportItemResult,
  QualificationImportResponse,
  ProfessionalRecord,
  ProfessionalRecordTenure,
  ProfessionalRecordPayload,
  PublicProfessionalRecordPayload,
  ProfessionalRecordCredentialResult,
  CareerExportDocument,
  ReliabilityReport,
  ReliabilityReportPayload,
  PublicReliabilityReportPayload,
  ReliabilityReportOutcome,
  ReliabilityReportFactor,
  OutcomeTemplatesCatalog,
  SandboxSeedSubject,
  SandboxSeedResult,
  SandboxResetResult,
  BookFilterQuery,
  ListUsersQuery,
  ListUsersPayload,
  SubjectSummary,
  BookSummaryPayload,
  BookSummaryBand,
} from './lib/client.js';
