// Provider + context
export { CreddaProvider } from './components/CreddaProvider.js';
export type { CreddaProviderProps } from './components/CreddaProvider.js';

// Hooks
export { useTrustToken } from './hooks/useTrustToken.js';
export type { UseTrustTokenResult } from './hooks/useTrustToken.js';

export { useScore } from './hooks/useScore.js';
export type { UseScoreResult } from './hooks/useScore.js';

// Offline credential verification (compact + W3C VC-JWT) + revocation
export { verifyTrustCredential, verifyVerifiableCredential, isCredentialRevoked } from './lib/credential.js';
export type {
  VerifiedCredential,
  TrustCredentialFacts,
  VerifyOptions,
  VerifiedVc,
  VerifyVcOptions,
  CredentialStatusEntry,
} from './lib/credential.js';

// Portable trust export verification
export { verifyTrustExport } from './lib/trustExport.js';
export type { VerifiedTrustExport } from './lib/trustExport.js';

// Webhook verification (for platforms receiving Credda trust events)
export { verifyWebhookSignature, constructWebhookEvent } from './lib/webhook.js';
export type {
  WebhookEvent, WebhookEventType, VerifyWebhookInput, WebhookVerification,
  ScoreEventData, DisputeResolvedData, MonitorTriggeredData, UsageQuotaWarningData,
  ScoreUpdatedEvent, ScoreBandChangedEvent, DisputeResolvedEvent, MonitorTriggeredEvent, UsageQuotaWarningEvent,
} from './lib/webhook.js';

// Web Bot Auth (RFC 9421) verification — the OPTIONAL second signature on a
// delivery, for receivers that terminate their own edge instead of relying on a
// WAF. Never a substitute for verifyWebhookSignature.
export { verifyWebBotAuthSignature } from './lib/webBotAuth.js';
export type {
  VerifyWebBotAuthInput, WebBotAuthVerification, WebBotAuthDirectory, WebBotAuthJwk,
} from './lib/webBotAuth.js';

// Client (for headless / non-React usage)
export { CreddaClient, CreddaError } from './lib/client.js';
export type {
  CreddaConfig,
  Plan,
  PlanFeature,
  PlanCatalog,
  BenchmarkCatalog,
  BenchmarkStatistics,
  BenchmarkCohort,
  BenchmarkDistributionPayload,
  UserBenchmarkPayload,
  WebhookEventDoc,
  WebhookEventCatalog,
  CreddaErrorContext,
  ErrorCodeDoc,
  ErrorCatalog,
  EnumValueDoc,
  EnumDoc,
  EnumCatalog,
  ChangelogEntry,
  DeprecationNotice,
  ApiChangelog,
  ReasonCodeDoc,
  ReasonCodeCatalog,
  ReasonCodeInstance,
  ReasonCodeResult,
  TrustPayload,
  TrustExport,
  AgentDeclaration,
  RegisterAgentInput,
  AgentSubject,
  AgentDetail,
  DeliveryRecord,
  DeliveryRecordDisclaimer,
  DeliveryReceiptsPayload,
  DidDocument,
  RegistryIssuer,
  TrustRegistry,
  CredentialIssuerMetadata,
  CredentialOfferResult,
  ScorePayload,
  ScoreBreakdown,
  ScoreExplainPayload,
  ScoreExplainFactor,
  ScoreHistoryPayload,
  ScoreDeltaPayload,
  ScoreComponent,
  ScoreComponentsPayload,
  EarningsQuery,
  VerifiedEarnings,
  EarningsSummary,
  EarningsPeriod,
  EarningsPlatformTotal,
  EarningsWindow,
  EarningsCredentialResult,
  TimelinePayload,
  TimelineItem,
  FactorDelta,
  ProjectionEventInput,
  ProjectionEventType,
  ScoreProjectionPayload,
  BatchScoreEntry,
  BatchScoresPayload,
  PlatformsPayload,
  ContributingPlatform,
  RiskPayload,
  UsagePayload,
  UsageDay,
  ReportEventInput,
  ReportEventResult,
  IngestEventType,
  ShareTokenResult,
  DisputeOutcome,
  DisputeResult,
  CreateWebhookInput,
  CreateWebhookResult,
  UpdateWebhookInput,
  WebhookConfig,
  WebhookSubscriptionEvent,
  WebhookTestResult,
  WebhookDelivery,
  RecentWebhookEvent,
  RecentWebhookEventDelivery,
  RecentWebhookEventsPayload,
  ScoreMonitor,
  CreateMonitorInput,
  UpdateMonitorInput,
  MonitorListPayload,
  ScreeningStatus,
  ScreeningJob,
  ScreeningResultItem,
  ScreeningListPayload,
  ScreeningResultsPayload,
  IngestTransform,
  IngestFieldRule,
  IngestMapping,
  IngestInput,
  IngestResultItem,
  IngestPayload,
  CreateMappingInput,
  StoredMapping,
  MappingListPayload,
  CreateImportInput,
  ImportStatus,
  ImportJob,
  ImportListPayload,
  ImportRowError,
  ImportRowWarning,
  ImportErrorsPayload,
  ConfirmationStatus,
  ConfirmationDecision,
  CreateConfirmationInput,
  ConfirmationRequest,
  ConfirmationCreateResult,
  ConfirmationBatchResult,
  ConfirmationListPayload,
  ConfirmationPreview,
  ConfirmationRespondResult,
  ActivationRow,
  CreateActivationCampaignInput,
  ActivationCampaignResult,
  ActivationFunnel,
  ActivationCampaignFunnelPayload,
  ReferenceRequestStatus,
  ReferenceDecision,
  ReferenceCategory,
  CreateReferenceInput,
  ReferenceRequest,
  ReferenceCreateResult,
  ReferenceListPayload,
  ReferencePreview,
  ReferenceRespondResult,
  PolicyMetric,
  PolicyDirection,
  PolicyComponentKey,
  ThresholdPolicy,
  CreatePolicyInput,
  UpdatePolicyInput,
  ThresholdPolicyListPayload,
  OpenBadgeAchievement,
  OpenBadgeAchievementsPayload,
  QualificationCategory,
  QualificationBreakdown,
  VerifiedProfilePayload,
  RecordQualificationInput,
  RecordQualificationResult,
  QualificationImportItemResult,
  QualificationImportResponse,
  ProfessionalRecord,
  ProfessionalRecordTenure,
  ProfessionalRecordPayload,
  PublicProfessionalRecordPayload,
  ProfessionalRecordCredentialResult,
  ReliabilityReport,
  ReliabilityReportPayload,
  PublicReliabilityReportPayload,
  ReliabilityReportOutcome,
  ReliabilityReportFactor,
  CareerExportDocument,
  OutcomeTemplatesCatalog,
  SandboxSeedSubject,
  SandboxSeedResult,
  SandboxResetResult,
  BookFilterQuery,
  ListUsersQuery,
  ListUsersPayload,
  SubjectSummary,
  BookSummaryPayload,
  BookSummaryBand,
} from './lib/client.js';
